COMP: Make BSplineDeformableTransformBase SetCoefficientImages virtual
Restored the `virtual` keyword for `AdvancedBSplineDeformableTransformBase::SetCoefficientImages`. which was removed by pull request https://github.com/SuperElastix/elastix/pull/1357 commit a533dd969231bf22e3fea9795dbc8f7fc55b5185 "STYLE: Make Get/Set CoefficientImages non-virtual, in BSpline Base", merged on Sep 3, 2025, included with 5.3.0 and 5.3.1.

Aims to fix:

    elastix\Common\OpenCL\Filters\itkGPUAdvancedBSplineDeformableTransform.h(70,3): error C3668: 'itk::GPUAdvancedBSplineDeformableTransform::SetCoefficientImages': method with override specifier 'override' did not override any base class methods