COMP: Use ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION (issue #216)
Addresses issue #216 "Cannot compile on win 32 platform", by fieres, confirmed by albertelonjobs. Fixes 32-bit Visual C++ compilation errors like:

> common\imagesamplers\itkImageToVectorContainerFilter.hxx(231): error C2664: cannot convert argument 1 from 'itk::ITK_THREAD_RETURN_TYPE (__cdecl *)(void *)' to 'itk::ThreadFunctionType'

`ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION` was introduced in ITK by Hans Johnson, "STYLE: Replace defines with constexpr and using statements", Sep 24, 2018, https://github.com/InsightSoftwareConsortium/ITK/commit/df93980bc026d102d3628ec983cbd15410d2d906

Note from Elastix maintainers: While this is clearly a proper fix, Elastix does not actively support 32-bit Windows compilation anymore.

Fix by Andrey Saenko (highemhigh)
Signed-off-by: ax1oma <ax1oma@yandex.ru>