COMP: Use ModifiedTimeType instead of unsigned long
Used `ModifiedTimeType` for modified time, instead of `unsigned long`, thereby fixing many Elastix/ITK5 compile errors, like this:

    error C2555: 'itk::ImageSpatialObject2::GetMTime': overriding virtual function return type differs and is not covariant from 'itk::SpatialObject::GetMTime'

Related ITK commits:

  @mstaring, 2012-09-24: https://github.com/InsightSoftwareConsortium/ITK/commit/cbf91c49e4e598adfc5b36e0d55c58c4dedae8d7
  @dzenanz, 2019-03-29: https://github.com/InsightSoftwareConsortium/ITK/commit/0598727d390e861f70b00a4a96a9c58e26b57036