BUG: Do not wrap any GoogleTest `ASSERT` into a lambda
Wrapping GoogleTest `ASSERT`s into lambda's appeared to be a clever workaround to avoid compile errors, like

> error C2440: 'return': cannot convert from 'void' to 'std::array<double,2>'

From elastix\Core\Main\GTesting\ElastixLibGTest.cxx as follows:

    template <unsigned VDimension>
    std::array<double, VDimension>
    ConvertStringsToArrayOfDouble(const std::vector<std::string> & strings)
    {
      ASSERT_EQ(strings.size(), VDimension);  // compile error!!!
      ...

Wrapped in a lambda as:

    [&strings] { ASSERT_EQ(strings.size(), VDimension); }();

However, the wrapped versions don't break the program flow anymore, as "expected" from an assert failure.

Fixed by using GoogleTest `EXCEPT` macro's instead, and the introduced `ELX_GTEST_EXPECT_FALSE_AND_THROW_EXCEPTION_IF(condition)`