COMP: Quick-fix ITKElastix error: 'itkCostFunction.h' file not found
Removed `#include <itkCostFunction.h>` and then simply defined `ElastixBase::CoordRepType` as `double` (which is the same type as `itk::CostFunction::ParametersValueType` anyway).

Aims to fix:

> _deps/elx-src/Core/Kernel/elxElastixBase.h:39:10: fatal error: 'itkCostFunction.h' file not found
itkElastixRegistrationMethodTest.cxx

At https://open.cdash.org/viewBuildError.php?buildid=6806022
ITKElastix pull request https://github.com/InsightSoftwareConsortium/ITKElastix/pull/66