COMP: Make using-declaration SetTransform protected instead of private
Avoided GCC errors like:

> error: 'void itk::ImageToImageMetric::SetTransform(itk::ImageToImageMetric::TransformType*)' is private within this context