COMP: Remove ITK_DISALLOW_COPY_AND_MOVE from UserData struct's
On GCC 12.2.2 (Debian) with C++20 enabled:

/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.hxx: In instantiation of ‘static void itk::ImageGridSampler<TInputImage>::MultiThreadedGenerateData(itk::MultiThreaderBase&, itk::ThreadIdType, const TInputImage&, const MaskType*, const typename Superclass::InputImageRegionType&, const SampleGridSpacingType&, std::vector<typename itk::ImageSamplerBase<TInputImage>::ImageSampleType>&) [with TInputImage = itk::Image<short int, 4>; itk::ThreadIdType = unsigned int; MaskType = itk::ImageMaskSpatialObject<4, unsigned char>; typename Superclass::InputImageRegionType = itk::ImageRegion<4>; Superclass = itk::ImageSamplerBase<itk::Image<short int, 4> >; SampleGridSpacingType = itk::Offset<4>; typename itk::ImageSamplerBase<TInputImage>::ImageSampleType = itk::ImageSample<itk::Image<short int, 4> >]’:
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.hxx:277:30:   required from ‘void itk::ImageGridSampler<TInputImage>::GenerateData() [with TInputImage = itk::Image<short int, 4>]’
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.hxx:253:1:   required from here
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.hxx:212:12: error: no matching function for call to ‘itk::ImageGridSampler<itk::Image<short int, 4> >::UserData::UserData(<brace-enclosed initializer list>)’
  212 |   UserData userData{ inputImage,
      |            ^~~~~~~~
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.h:169:32: note: candidate: ‘itk::ImageGridSampler<TInputImage>::UserData::UserData(itk::ImageGridSampler<TInputImage>::UserData&&) [with TInputImage = itk::Image<short int, 4>]’ (deleted)
  169 |     ITK_DISALLOW_COPY_AND_MOVE(UserData);
      |                                ^~~~~~~~
/home/matt/src/ITK/Modules/Core/Common/include/itkMacro.h:397:3: note: in definition of macro ‘ITK_DISALLOW_COPY_AND_MOVE’
  397 |   TypeName(TypeName &&) = delete;                  \
      |   ^~~~~~~~
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.h:169:32: note:   candidate expects 1 argument, 4 provided
  169 |     ITK_DISALLOW_COPY_AND_MOVE(UserData);
      |                                ^~~~~~~~
/home/matt/src/ITK/Modules/Core/Common/include/itkMacro.h:397:3: note: in definition of macro ‘ITK_DISALLOW_COPY_AND_MOVE’
  397 |   TypeName(TypeName &&) = delete;                  \
      |   ^~~~~~~~
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.h:169:32: note: candidate: ‘itk::ImageGridSampler<TInputImage>::UserData::UserData(const itk::ImageGridSampler<TInputImage>::UserData&) [with TInputImage = itk::Image<short int, 4>]’ (deleted)
  169 |     ITK_DISALLOW_COPY_AND_MOVE(UserData);
      |                                ^~~~~~~~
/home/matt/src/ITK/Modules/Core/Common/include/itkMacro.h:395:3: note: in definition of macro ‘ITK_DISALLOW_COPY_AND_MOVE’
  395 |   TypeName(const TypeName &) = delete;             \
      |   ^~~~~~~~
/home/matt/src/elastix/Common/ImageSamplers/itkImageGridSampler.h:169:32: note:   candidate expects 1 argument, 4 provided
  169 |     ITK_DISALLOW_COPY_AND_MOVE(UserData);
      |                                ^~~~~~~~
/home/matt/src/ITK/Modules/Core/Common/include/itkMacro.h:395:3: note: in definition of macro ‘ITK_DISALLOW_COPY_AND_MOVE’
  395 |   TypeName(const TypeName &) = delete;             \
      |   ^~~~~~~~