COMP: Require ITK 5.1 rather than ITK 5.0
Avoids compilation errors that would occur when trying to build with ITK 5.0, like:

> Core\ComponentBaseClasses\elxTransformBase.hxx(40,10): fatal error C1083: Cannot open include file: 'itkCommonEnums.h': No such file or directory

Follow-up to commit 092d289ab2a5393193acece2b42b08ab3a910f8f "COMP: Upgrade ITK from v5.0.1 to v5.1.0 (ITK_LEGACY_REMOVE)"