COMP: Removed AdvancedTransform::InverseJacobianPositionType
Removed both `InverseJacobianPositionType` and `ComputeJacobianWithRespectToPosition(p, j)` from `AdvancedTransform`.

Neither the type nor the member function appear to be used. The type definition causes compilation errors with ITK4:

    itkAdvancedTransform.h(116): error C2039: 'InverseJacobianPositionType': is not a member of 'itk::Transform'