STYLE: Make local constexpr variables in GTests `static`
Added `static` to ensure that those local variables are evaluated at
compile-time. Following a suggestion by "C++ Weekly With Jason Turner"
(https://www.youtube.com/@cppweekly) episode 312 - Stop Using `constexpr`
(And Use This Instead!), https://www.youtube.com/watch?v=4pKtPWcl1Go

Using Notepad++, Replace in Files:

    Find what:   (constexpr .+=.+;)
    Replace with:   static \1
    [v] Match case
    (*) Regular expression
    Filter: *GTest.cxx

Excluded the local variable `pixelTypeNames` from `GetPixelTypeName()`, to avoid compilation errors like (macos-12/Xcode_14.2 clang):

> Core/Main/GTesting/ElastixLibGTest.cxx:54:25: error: static variable not permitted in a constexpr function