COMP: Fix VS2015 TypeList.h(539): error C2059: syntax error: 'template'
Add a workaround for Visual Studio < 2017, to avoid VS2015 compile errors when building with OpenCL, reported by Denis (@dpshamonin):

> TypeList.h(539): error C2059: syntax error: 'template'

Partially reverts "COMP: fixed the VisitDimension OpenCL compilation issues" commit c9261630ee05a4ec72d8532151fedd79e3954258 (@dpshamonin Mar 5, 2019).