COMP: Add missing elastix `#include` directives to elxGTestUtilities.h
Aims to fix macos-11/clang errors saying "error: use of undeclared identifier 'elx'".