COMP: Add missing typeinfo include
To address:

  _deps/elastix_fetch-src/Core/Main/elxPixelType.h:31:50: error: you need to include <typeinfo> before using the 'typeid' operator