STYLE: Remove obsolete externalproject (elxExternalProject)
elxExternalProject is no longer maintained. An attempt to build the project causes compilation error, saying:

> elastix\dox\externalproject\itkTimerTest.cxx(14,10): fatal error C1083: Cannot open include file: 'elxTimer.h': No such file or directory

For the record, elxExternalProject was introduced by Stefan Klein, with commit 81168bedd3bcc049ee96305f3e471edc88509648, 9 January 2011.