COMP: Add `(void)` casts to `inputPixelTypeHolder` parameters of GTests
Fixes MSVC /W4 warnings, saying:
> warning C4100: 'inputPixelTypeHolder': unreferenced formal parameter

Note that `[[maybe_unused]]` cannot be used in these case, because of a compiler bug in MSVC 2022, which would produce:
> error C2187: syntax error: 'attribute specifier' was unexpected here

This error occurs with an `auto` parameter of a lambda, when the capture list `[]` is empty.