BUG: Add `Size` to Testing/PythonTests/TransformParameters
Even when the transform is only applied to points, `itk::TransformixFilter` requires a `Size` parameter. Otherwise it says something like:

> ERROR: transformix terminated because of the following exception:
> Exception type: class itk::ExceptionObject
> itk::ExceptionObject (000000E76552E790)
> Location: "void __cdecl itk::TransformixFilter<class itk::Image<float,3> >::GenerateOutputInformation(void)"
> File: C:\X\src\elx\elx-dev\Core\Main\itkTransformixFilter.hxx
> Line: 287
> Description: ITK ERROR: TransformixFilter(000002B46DB7BD10): No entry Size found in transformParameterMap

Also fixed the `Index` of the test 3D translation.