COMP: Fixed error MultiResolutionImageRegistrationMethod2::MakeOutput
Removed `return 0` from `MultiResolutionImageRegistrationMethod2::MakeOutput(unsigned int)`, to fix a compile error when using ITK5:

    error C2440: 'return': cannot convert from 'int' to 'itk::SmartPointer<itk::DataObject::Self>'

Refactored this member functions, avoiding "warning C4702: unreachable code" (Visual C++ Warning Level 4), according to the following revision of the corresponding ITK `MakeOutput` member functions:
  https://github.com/InsightSoftwareConsortium/ITK/commit/ff9996929be9189c6bad5a40fe57f039d4397891