COMP: Add missing `#include <cassert>` directives
Aims to prevent errors like:

> Components/Optimizers/StandardStochasticGradientDescent/itkStochasticGradientDescentOptimizer.cxx:309:3: error: 'assert' was not declared in this scope

At https://my.cdash.org/viewBuildError.php?buildid=2537950
(Build Name: SuperElastix/elastix-ubuntu-22.04-WIP-back-to-ITK-v530-9a39f9931e9207e164c410a92c71e09f76002ee4)