COMP: Fix ITK5 compile errors, itkCompute*.hxx using 0 for SmartPointer
Removed "0" (zero) as initial value for smart pointers (`itk::SmartPointer`), in two elastix/Common/itkCompute*.hxx files. Fixes compile errors when using ITK 5:

    error C2440: 'initializing': cannot convert from 'int' to 'itk::SmartPointer'

Noted that for a smart pointer, the default-constructor already initializes to null.