COMP: Remove using ElastixType, ConfigurationType from TransformBase
Removed two using-declarations that appear to cause compile errors from GNU 4.8.2, trying to compile ITKElastix:

> _deps/elx-src/Core/ComponentBaseClasses/elxTransformBase.h:149:20: error: ‘ConfigurationType’ is not a class, namespace, or enumeration

> _deps/elx-src/Core/ComponentBaseClasses/elxTransformBase.h:155:20: error: ‘ElastixType’ is not a class, namespace, or enumeration

At https://github.com/InsightSoftwareConsortium/ITKElastix/pull/66/checks?check_run_id=1199552577#step:4:2197