COMP: Move #include "itkOpenCL..." from elxElastixMain.h to elx*Main.cxx
Moved the `#include "itkOpenCLContext.h"` from elxElastixMain.h to elxElastixMain.cxx and elxTransformixMain.cxx, hoping to ease fixing the error:

> /work/_skbuild/linux-x86_64-3.5/cmake-build/_deps/elx-src/Core/Kernel/elxElastixMain.h:33:10: fatal error: 'itkOpenCLContext.h' file not found

at https://github.com/InsightSoftwareConsortium/ITKElastix/pull/58/checks?check_run_id=1096122268#step:4:2894

(Pull request https://github.com/InsightSoftwareConsortium/ITKElastix/pull/58 "ENH: Switch to latest version of SuperElastix/elastix (using ITK 5.1.1)")