COMP: Fix ITK v5.1rc03 build error from MyStandardResampler::PointType
Fixes the following Visual C++ compile error, which occurs when upgrading from ITK 5.0.1 to ITK v5.1rc03:

> error C2039: 'PointType': is not a member of 'itk::ResampleImageFilter'