COMP: Add missing itkMacro.h include
For itkGenericExceptionMacro.

To address:

  _deps/elastix_fetch-src/Core/Main/elxPixelType.h:33:30: error: expected expression