COMP: Add missing itkCastImageFilter.h include to elxResampleBase.h
To address:

```
In file included from /work/_skbuild/linux-x86_64-3.10/cmake-build/_deps/elx-src/Core/Kernel/elxElastixTemplate.h:30:
/work/_skbuild/linux-x86_64-3.10/cmake-build/_deps/elx-src/Core/ComponentBaseClasses/elxResamplerBase.h:229:12: error: no member named 'CastImageFilter' in namespace 'itk'
      itk::CastImageFilter<InputImageType, itk::Image<TResultPixel, InputImageType::ImageDimension>>::New();
      ~~~~~^
```