COMP: Fix error w/ ITK5, trying to initialize itk::SmartPointer by zero
Fixed "error C2440: 'initializing': cannot convert from 'int' to 'itk::SmartPointer'" (five times), by using the default-constructor of itk::SmartPointer, instead of the obsolete conversion from 0.