COMP: Include itkMacro.h instead of itkExceptionObject.h
To address

/home/matt/src/ITK/Modules/Core/Common/include/itkExceptionObject.h:19:2:
error: "Do not include itkExceptionObject.h directly,  include
itkMacro.h instead."

when building against ITK Git master.