COMP: Upgrade Ubuntu version at Azure pipelines CI from 18.0.4 to 20.0.4
The image of Ubuntu 18.0.4 still has Python 3.6, which has reached "the end-of-life phase of its release cycle", as of 2021-12-2, according to https://peps.python.org/pep-0494/

Ubuntu 20.04.4 has installed Python3 3.8.10 out of the box, according to https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

Aims to solve a Python error from TransformixTest (under construction), saying:

> TypeError: __init__() got an unexpected keyword argument 'capture_output'