COMP: Restore the old TransformBase::RegistrationType typedef
The more elegant `using typename Superclass::RegistrationType`, introduced with bdebf83a0298ce9f27ca0c0978d03eef5a1aae2b ("STYLE: Modernize code of elxTransformBase", 23 September 2020) appeared to trigger errors from GCC 4.8.2, trying to compile ITKElastix:

> _deps/elx-src/Core/ComponentBaseClasses/elxTransformBase.h:202:20: error: ‘RegistrationType’ is not a class, namespace, or enumeration

At https://github.com/InsightSoftwareConsortium/ITKElastix/pull/66/checks?check_run_id=1202143512#step:4:2212

Removed other "using typename Superclass::type" using-declarations, as they appear unused. (They were redundant anyway.) Replaced an internal use of `ConfigurationPointer` by `const auto`, which is also more const-correct.