COMP: fixed the VisitDimension OpenCL compilation issues
Reported by @kaspermarstal

opencl fixed pyramid:/home/kasper/dev/Elastix/Common/TypeList.h:494:45: error: expected primary-expression before ‘>’ token

    visitor.CLANG_TEMPLATE operator()< Head >( );and/home/kasper/dev/Elastix/Components/FixedImagePyramids/OpenCLFixedGenericPyramid/elxOpenCLFixedGenericPyramid.cxx:21:45:   required from here

/home/kasper/dev/Elastix/Common/TypeList.h:744:63: error: return-statement with a value, in function returning 'void' [-fpermissive]

    return impl.CLANG_TEMPLATE operator()< Visitor >( visitor );